# config/elastic_apm.yml:

# Set service name - allowed characters: a-z, A-Z, 0-9, -, _ and space
# Defaults to the name of your Rails app
service_name: <%= ENV['ES_APM_SERVICE_NAME'] %>

# Use if APM Server requires a token
secret_token: <%= ENV['ES_APM_SECRET_TOKEN'] %>

# Set custom APM Server URL (default: http://localhost:8200)
server_url: <%= ENV['ES_APM_URL'] %>